### ISSUE TITLE
many vehicles fail to detect 

### ISSUE THREAD

**Issue by helxsz** [nshaud/DeepNetsForEO#16]
In the test images from ISPRS images, the predicted image is 96% success. However I have screenshoted a satellite image for the testing, as shown below.

![33](https://user-images.githubusercontent.com/669670/28489373-6c2f4482-6ef5-11e7-822a-74024ca0f72b.png)

after using the inference_patches, the result is shown below, it seems that at 50% area are failing to predict the crowed vehicles in the parking lot. The up-left side is correctly predicted but can't tell the instances of the vehicles.

![33 png_predicted](https://user-images.githubusercontent.com/669670/28489376-7f10436c-6ef5-11e7-8708-ffd9b3ac7371.png)

I wonder is it because of the training data not enough to predict this case or the vehicles here are very small objects, any approach to improve ? 

Additionally, does each image put into the network has to be stick to 128x128 because of our training data is 128x128 size, currently in this test the testing image is roughly 200x200

**Comment by nshaud** [comment]
There are two questions in this issue : 

  1. Why does it fail on your image ?
  2. What image size can we use for inference ?

Regarding *1)*, I think this is mainly because your satellite image does not have the same ground sampling distance (GSD, i.e. ground resolution) as the training data. The pre-trained models in this repo are trained on very high resolution data (5cm/px for RGB Potsdam). If you try to interpolate your image at this resolution, the results will probably improve.

Regarding *2)*, since the network we used (SegNet) is fully convolutional, it supports any input size. However, Caffe asks for a fixed size input so there might be some code modification needed here.

**Comment by helxsz** [comment]
The image was extracted from google map in zoom 20, so far I don't know what is the ground sampling distance for google map satellite
